plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jarrredapps.win8remastered'

    compileSdk 36

    defaultConfig {
        applicationId 'com.jarrredapps.win8remastered'
        minSdk 23
        targetSdk 36

        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false

            proguardFiles(
                getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro'
            )
        }
    }
}

dependencies {
    implementation fileTree(
        dir: 'libs',
        include: ['*.jar']
    )
}
